name: adventofcode2022
description: Solutions to the advent of code 2021
version: 0.1.0
homepage: https://github.com/traveling-developer/Advent-of-Code-2022
repository: https://github.com/traveling-developer/Advent-of-Code-2022

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  http: ^0.13.5
  collection: ^1.17.0
  quiver: ^3.1.0
  graphs: ^2.2.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
